language: python
python: 3.6
sudo: required
matrix:
  include:
    - os: osx
      language: generic
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           PLAT=manylinux1_i686
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

install:
  - if [ -n "$DOCKER_IMAGE" ]; then
      docker pull $DOCKER_IMAGE;
    else
      brew install cmake pyenv;
    fi
script:
  - if [ -n "$DOCKER_IMAGE" ]; then
      docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels-using-docker.sh;
    else
      travis/build-wheels-using-mac.sh;
    fi
before_deploy:
  - if [ -n "$DOCKER_IMAGE" ]; then
      cd build/python;
      sudo chown -R travis:travis /home/travis/;
      rm dist/*;
      cp wheelhouse/* dist/.;
    fi
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: "ksgwr"
  password:
    secure: fdmZ+PMys1077Yq8x6xwWqHh8fzaxj1PojngHXlDvGgcbXNrTjXMUoyifSpSocp0YJrB7sQgeOuDPWD5dC/kinQ1my+v5NgNS2Oy/l/4mhodpOwThqYiAp6wOQjLu8GgMBFFVW6nij2ZCcJA/mBPoeZFb9pbf7c6Mfl1ENLq/ndpNn4DVrSA+IfkygidPZrpDhgWi0QOIVkUbztcSVOWRRQH5lLZv4Zkn3nUNtbvYpUkI1dnKYLKVLgPOG9Uwya5xOhlSJm/j3DPBMaV1H7tQXn0lLrTpFL34FZtpRn97oM1r+wJo9QVX+BLCuQ3E2IhqLlHJOGwoNXVctZNasdGnmphERZNzOzOig3eUrKKcWD34C2hw/3+jY3qYzrNYEVA52DmW93je/6XXBaxtg0zuAXGlQhS2nDqEzA9fPKibx3hbsfHCzlNj5wzMb0bAAvHp+T1xDaX1HXcA6k5lXvNlzmdUYGJYarQ7G9odQtxR4mZoJ+vcO2iaBP3nHRhyOc3tpv+0uG0FGa44AY1GTSuWI9PgOUdgWlAcfQw2eNv+OzNEnbG30ufzGIn2kzG5IHuBawmhv8kVicOfxq8zHLBvKSv41JPVt5YphGeDZsukAjgvv1BHBx1xAnYJS3ZK0aZ3i5oMDuNtI2lO+qzC8fI9sHnCBdA2W65m+vxqcj4Vhs=
  #on:
  #  tags: true
  distributions: "bdist_wheel"
  skip_cleanup: true
  skip_existing: true
