branches:
  only:
    - master

#skip_non_tags: true

environment:
  PYPI_USERNAME: ksgwr
  TEST_PYPIPASSWORD:
    secure: NeiXDBjvTet+017Bsek8ZQ==

image: Visual Studio 2017
platform:
  - x64
  - Win32
configuration: Debug

clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

build_script:
  - cmd: call ci\build-wheels-using-windows.bat %platform% || exit /b %errorlevel%

artifacts:
  - path: build\java\build
  - path: build\python\dist\*.whl

deploy_script:
  - cmd: set TESTREPO=https://test.pypi.org/legacy/
  - python -m pip install twine
  - set HOME=%USERPROFILE%
  - python -m twine upload --skip-existing build\python\dist\* --repository-url %TESTREPO% -u %PYPI_USERNAME% -p %TEST_PYPIPASSWORD%